version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Jagadhis-prod
    ports:
      - "8080:80"

    # environment:
    #   - REACT_APP_NAME=Jagadhis-prod
    #   - WATCHPACK_POLLING=true
    # env_file:
    #   - ./.env  
